/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tocomfome.gui;

import java.util.Iterator;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import tocomfome.models.Employee;
import tocomfome.parsers.EmployeeParser;

/**
 *
 * @author fabio
 */
public class UserLoginJFrame extends javax.swing.JFrame {
    private static final String FILL_BOTH_FIELDS_MESSAGE = "Ambos os campos devem estar preenchidos";
    private static final String INCORRECT_FIELDS = "Login incorreto ou senha incorreta";

    private EmployeeParser employeeParser;


    /**
     * Creates new form UserLoginJFrame
     */
    public UserLoginJFrame() {
        initComponents();

        try {
            this.employeeParser = new EmployeeParser();
        } catch(Exception ex) {
            Logger.getLogger(UserLoginJFrame.class.getName()).log(Level.SEVERE, null, ex);
            System.exit(0);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        userLogin = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        userPassword = new javax.swing.JPasswordField();
        enterButton = new javax.swing.JButton();
        errorMessage = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("Noto Sans", 0, 36)); // NOI18N
        jLabel1.setText("Login");

        jLabel2.setText("login:");

        jLabel3.setText("Password:");

        enterButton.setText("Entrar");
        enterButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enterButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(userPassword)
                            .addComponent(userLogin)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(169, 169, 169)
                        .addComponent(jLabel1)
                        .addGap(0, 175, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(enterButton)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(errorMessage, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(userLogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(userPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(enterButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(errorMessage, javax.swing.GroupLayout.DEFAULT_SIZE, 39, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void enterButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enterButtonActionPerformed
        final String login = this.userLogin.getText().trim();
        final String password = String.copyValueOf(this.userPassword.getPassword()).trim();

        if (login.length() > 0 && password.length() > 0) {
            this.verifyUserAccess(login, password);
        } else {
            this.errorMessage.setText(FILL_BOTH_FIELDS_MESSAGE);
        }
    }//GEN-LAST:event_enterButtonActionPerformed

    private void verifyUserAccess(final String login, final String password) {
        List<Employee> employees = this.employeeParser.getEmployees();
        boolean userHasAccess = false;

        final Iterator<Employee> employeeIterator = employees.iterator();
        while (employeeIterator.hasNext() && (userHasAccess != true)) {
            final Employee employee = employeeIterator.next();

            if (employee.getLogin().equals(login) && employee.getPassword().equals(password)) {
                userHasAccess = true;
            }
        }

        if (userHasAccess) {
            this.displayCurrentOrdersJFrame();
        } else {
            this.errorMessage.setText(INCORRECT_FIELDS);
        }
    }

    private void displayCurrentOrdersJFrame() {
        this.errorMessage.setText("");
        this.setVisible(false);

        final CurrentOrdersJFrame currentOrdersJFrame = new CurrentOrdersJFrame(this);
        currentOrdersJFrame.setVisible(true);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton enterButton;
    private javax.swing.JLabel errorMessage;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField userLogin;
    private javax.swing.JPasswordField userPassword;
    // End of variables declaration//GEN-END:variables
}
